version: '3'

services:
  redis:
    image: redis:latest
    ports:
        - "6378:6379"
    command: redis-server
  db:
    #image: postgres
    build:
        context: .
        dockerfile: Dockerfile_postgres
    container_name: locus_db
    volumes:
      - .:/locus_dir_db
    ports:
        - "5431:5432"
  web:
    build:
        context: .
        dockerfile: Dockerfile_web
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && daphne -b 0.0.0.0 -p 8000 Locus.asgi:application"
    #python3 manage.py runserver 0.0.0.0:8000"
    #daphne -b 0.0.0.0 -p 8000 Locus.asgi:channel_layer
    container_name: locus_web
    volumes:
      - .:/locus_dir_web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker_twitter_url:
    build:
        context: .
        dockerfile: Dockerfile_web
    command: python manage.py runworker twitter_url_searcher
    container_name: locus_twitter_url_searcher
    volumes:
       - .:/locus_dir_web
    depends_on:
       - redis
