# Generated by Django 2.2.7 on 2019-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('googleCrawlerOfficial', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('username', models.CharField(max_length=60)),
                ('userlink', models.URLField()),
                ('link', models.URLField()),
                ('likes', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('google', models.ManyToManyField(to='googleCrawlerOfficial.InternetResult')),
                ('searches', models.ManyToManyField(to='search.SearchParameters')),
            ],
        ),
    ]
