# Generated by Django 2.2 on 2019-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('username', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=60)),
            ],
        ),
    ]
