# Generated by Django 2.2 on 2019-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='userlink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
