# Generated by Django 2.2.7 on 2019-11-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetCrawler', '0002_auto_20191126_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='google',
        ),
    ]
