# Generated by Django 2.2.7 on 2019-11-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0003_auto_20191130_1806'),
        ('tweetCrawler', '0003_remove_tweet_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='google',
            field=models.ManyToManyField(to='googleCrawlerOfficial.InternetResult'),
        ),
    ]
