# Generated by Django 2.2.7 on 2019-12-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetCrawler', '0004_tweet_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='searches',
            field=models.ManyToManyField(related_name='tweets', to='search.SearchParameters'),
        ),
    ]
