# Generated by Django 2.2.7 on 2019-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0004_auto_20191201_2324'),
        ('tweetCrawler', '0005_auto_20191201_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='google',
        ),
        migrations.AddField(
            model_name='tweet',
            name='internet_articles',
            field=models.ManyToManyField(related_name='tweets', to='googleCrawlerOfficial.InternetResult'),
        ),
    ]
