# Generated by Django 2.2.7 on 2019-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleResultOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField()),
                ('searches', models.ManyToManyField(to='search.SearchParameters')),
            ],
        ),
    ]
