# Generated by Django 2.2.7 on 2019-11-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='googleresultofficial',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='googleCrawlerOfficial.Domain'),
        ),
    ]
