# Generated by Django 2.2.2 on 2019-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='GoogleResultOfficial',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
