# Generated by Django 2.2.7 on 2019-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0003_auto_20191130_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetresult',
            name='searches',
            field=models.ManyToManyField(related_name='internet_articles', to='search.SearchParameters'),
        ),
    ]
