# Generated by Django 2.2.7 on 2019-12-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetresult',
            name='snippet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='internetresult',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
