# Generated by Django 2.2.7 on 2019-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedArticle',
            fields=[
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultArticle',
            fields=[
                ('similarity', models.FloatField()),
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('searches', models.ManyToManyField(to='search.SearchParameters')),
            ],
        ),
    ]
