# Generated by Django 2.2.7 on 2019-12-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0001_initial'),
        ('searchEngine', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedArticle',
            fields=[
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultArticle',
            fields=[
                ('similarity', models.FloatField()),
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchEngine.Domain')),
                ('searches', models.ManyToManyField(related_name='db_articles', to='search.SearchParameters')),
                ('top_words', models.ManyToManyField(to='database.TopWord')),
                ('tweets', models.ManyToManyField(related_name='db_articles', to='twitter.Tweet')),
            ],
        ),
    ]
