# Generated by Django 2.2.7 on 2019-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultarticle',
            name='top_words',
            field=models.TextField(default=''),
        ),
    ]
