# Generated by Django 2.2.7 on 2019-11-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawlerOfficial', '0002_auto_20191126_2050'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultarticle',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='googleCrawlerOfficial.Domain'),
        ),
    ]
