# Generated by Django 2.2.2 on 2019-11-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('page', models.TextField()),
                ('date', models.DateField(null=True)),
                ('link', models.URLField(unique=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
