# Generated by Django 2.2.2 on 2019-11-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_resultarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedarticle',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='resultarticle',
            name='link',
            field=models.URLField(),
        ),
    ]
