# Generated by Django 2.2.7 on 2019-11-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_resultarticle_top_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultarticle',
            name='top_words_counts',
            field=models.IntegerField(default=0),
        ),
    ]
