# Generated by Django 2.2.7 on 2019-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_resultarticle_top_words_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultarticle',
            name='top_words_counts',
        ),
        migrations.RemoveField(
            model_name='resultarticle',
            name='top_words',
        ),
        migrations.AddField(
            model_name='resultarticle',
            name='top_words',
            field=models.ManyToManyField(to='database.TopWord'),
        ),
    ]
