# Generated by Django 2.2.7 on 2019-11-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191125_1755'),
        ('database', '0002_resultarticle_domain'),
    ]

    operations = [
    ]
