# Generated by Django 2.2.7 on 2019-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetCrawler', '0002_auto_20191126_1854'),
        ('database', '0005_merge_20191126_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultArticle',
            name='tweets',
            field=models.ManyToManyField(to='tweetCrawler.Tweet'),
        ),
    ]
