# Generated by Django 2.2.7 on 2019-12-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_resultarticle_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultarticle',
            name='tweets',
            field=models.ManyToManyField(related_name='db_articles', to='tweetCrawler.Tweet'),
        ),
    ]
