# Generated by Django 2.2.7 on 2019-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191201_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultarticle',
            name='searches',
            field=models.ManyToManyField(related_name='db_articles', to='search.SearchParameters'),
        ),
    ]
