# Generated by Django 2.2.2 on 2019-06-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleCrawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleresult',
            name='date',
        ),
        migrations.RemoveField(
            model_name='googleresult',
            name='time',
        ),
    ]
