# Generated by Django 2.2.7 on 2019-12-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearcherStatus',
            fields=[
                ('searcher', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('queued', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('twitter_search', models.BooleanField(default=False)),
                ('google_search', models.BooleanField(default=False)),
                ('db_search', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Domain')),
            ],
        ),
    ]
