# Generated by Django 2.2.7 on 2019-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerStatus',
            fields=[
                ('crawler', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('queued', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('twitter_search', models.BooleanField(default=False)),
                ('google_search', models.BooleanField(default=False)),
                ('db_search', models.BooleanField(default=False)),
            ],
        ),
    ]
