# Generated by Django 2.2.7 on 2019-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerStatus',
            fields=[
                ('crawler', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('in_progress', models.IntegerField()),
                ('success', models.IntegerField()),
                ('failure', models.IntegerField()),
            ],
        ),
    ]
