# Generated by Django 2.2.7 on 2019-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchparameters',
            name='db_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='google_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='twitter_search',
            field=models.BooleanField(default=False),
        ),
    ]
