# Generated by Django 2.2.7 on 2019-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearcherStatus',
            fields=[
                ('searcher', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('queued', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CrawlerStatus',
        ),
    ]
