# Generated by Django 2.2.7 on 2019-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_crawlerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerstatus',
            name='failure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlerstatus',
            name='in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlerstatus',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
