# Generated by Django 2.2.7 on 2019-11-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191124_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchparameters',
            old_name='url',
            new_name='link',
        ),
    ]
