# Generated by Django 2.2.7 on 2019-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191130_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerstatus',
            name='pending',
            field=models.IntegerField(default=0),
        ),
    ]
