# Generated by Django 2.2.7 on 2019-11-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_crawlerstatus_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerstatus',
            old_name='pending',
            new_name='is_pending',
        ),
    ]
