# Generated by Django 2.2.7 on 2019-11-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191130_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerstatus',
            old_name='is_pending',
            new_name='waiting',
        ),
    ]
